### ISSUE TITLE
TEST MODULE SPANISH

### ISSUE THREAD

**Issue by olimpa** [hoangvu12/kaguya-modules#57]
[tioanime.kmodule.zip](https://github.com/hoangvu12/kaguya-modules/files/14414215/tioanime.kmodule.zip)

**I'm trying to understand the function well so that it runs in the app, when I add it I get that the metadata is missing?**

**Comment by hoangvu12** [comment]
![image](https://github.com/hoangvu12/kaguya-modules/assets/68330291/fc3bcdab-8b4a-4ff0-9f83-61266ebfc2e4)
![image](https://github.com/hoangvu12/kaguya-modules/assets/68330291/5a18602a-f827-48c5-8c7a-d0985dc650fc)

Does it has metadata file?
